default: build

build:
    cd "{{justfile_directory()}}" && mkdir -p out && xelatex -interaction=nonstopmode -output-directory=out main.tex
    cd "{{justfile_directory()}}" && xelatex -interaction=nonstopmode -output-directory=out main.tex

publish: build
    cd "{{justfile_directory()}}" && cp out/main.pdf ../TestPlanReport.pdf

clean:
    cd "{{justfile_directory()}}" && rm -rf out
