[mgr]
cwd = { fg = "cyan" }

find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

symlink_target = { italic = true }

marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightcyan",   bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "black", bg = "yellow" }

border_symbol = "│"
border_style  = { fg = "gray" }

syntect_theme = ""

[tabs]
active   = { bg = "blue", bold = true }
inactive = { fg = "blue", bg = "gray" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { bg = "blue", bold = true }
normal_alt  = { fg = "blue", bg = "gray" }

select_main = { bg = "red", bold = true }
select_alt  = { fg = "red", bg = "gray" }

unset_main = { bg = "red", bold = true }
unset_alt  = { fg = "red", bg = "gray" }

[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "▐", close = "▌" }

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "darkgray" }
perm_type  = { fg = "green" }
perm_read  = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec  = { fg = "cyan" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "green", bg = "black" }
progress_error  = { fg = "yellow", bg = "red" }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "blue" }
title      = { fg = "blue" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "blue" }
title  = { fg = "blue" }

# Table
tbl_col  = { fg = "blue" }
tbl_cell = { fg = "yellow", reversed = true }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", bold = true }

# : }}}


# : Help menu {{{

[help]
on      = { fg = "cyan" }
run     = { fg = "magenta" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }

# : }}}

