edition = "2024"
style_edition = "2024"
max_width = 120
use_small_heuristics = "Max"
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
