background = 0x000000ff
base = 0x000000ff
text = 0xffffffff
alternate_base = 0x000000ff
bright_text = 0xffffffff
accent = 0x40e0d0ff
accent_secondary = 0xff3a4cff

h1_size = 24
h2_size = 20
h3_size = 16
font_size = 12
small_font_size = 9

icon_theme =
font_family = "Oziosevka"
font_family_monospace = "Oziosevka"
rounding_large = 12
rounding_small = 6
