background = 0x00000000
base = 0x00000000
text = 0xffffffff
alternate_base = 0x00000000
bright_text = 0xffffffff
accent = 0x40e0d0ff
accent_secondary = 0xff3a4cff

h1_size = 24
h2_size = 20
h3_size = 16
font_size = 12
small_font_size = 9

# icon_theme
font_family = "oziosevka"
font_family_monospace = "oziosevka"
rounding_large = 12
rounding_small = 5
