default: build

build: diagrams
    cd "{{justfile_directory()}}" && xelatex -interaction=nonstopmode -output-directory=out main.tex
    cd "{{justfile_directory()}}" && xelatex -interaction=nonstopmode -output-directory=out main.tex

diagrams:
    cd "{{justfile_directory()}}" && mkdir -p out/generated && for file in diagrams/*.puml; do plantuml -o ../out/generated "$file"; done

clean:
    cd "{{justfile_directory()}}" && rm -rf out
